CREATE TABLE IF NOT EXISTS jams (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) UNIQUE NOT NULL,
  description VARCHAR(255) NOT NULL,
  duration INTEGER NOT NULL,
  start_date DATE NOT NULL DEFAULT CURRENT_DATE
);